/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a.medical.patient.tracker;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Muzaffer
 */
public class patientLogin extends javax.swing.JFrame {
    
    DBservice db = new DBservice();
    
    
    
    
    Register currentperson;
    
  
   //  ArrayList<Register> list = Register.pationlist;
     
     
    
    
    
    public patientLogin() {
        
        
        initComponents();
               
          
         
        
    }

    
    /*
    
    public void userlogin(){
        
           
       
        String Tcnumber = jTextField2.getText();
        
        
        
        String password = jPasswordField1.getText();
           
       
            if(currentperson==null)
         {


           JOptionPane.showMessageDialog(this,"unsuccesfull ","error",JOptionPane.INFORMATION_MESSAGE);
         }
            
            int i;
        for(i =0; i< list.size();i++){
 
        if(list.get(i).patientNumber.equals(PatientId)&& list.get(i).TcNumber.equals(Tcnumber)&&list.get(i).Name.equals(Name)&& list.get(i).Surname.equals(Lastname)&& list.get(i).Mobilenumber.equals(Mobilenumber)&&list.get(i).Birthdate.equals(Birthdate)&&list.get(i).Weight.equals(weight)&&list.get(i).height.equals((height))&&list.get(i).Password.equals(password)){
            
            
            System.out.println("GJ");
            
           Register.patientinf.add(list.get(i));
            
                       
                
            
            
            JOptionPane.showMessageDialog(this,"successfully loggin","Login Complete",JOptionPane.INFORMATION_MESSAGE);
            
            patientOptionScreen optionscreen = new patientOptionScreen();
            optionscreen.setVisible(true);
            optionscreen.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            
            
            
 
        
    }
       
        
        
   
    
    
    }
        
        
        
        
    }  
    
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        login = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("TC Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 208, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Login");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Password");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        register.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        register.setText("Register Here");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));

        login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 137, -1));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 208, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a/medical/patient/tracker/backbutton (1).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
       
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        
        String tcnumber = jTextField2.getText();
        String password = jPasswordField1.getText();
        
       if(db.checkLogin(tcnumber, password)){
           
           patientOptionScreen p= new patientOptionScreen(tcnumber);
           p.setVisible(true);
           p.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
           dispose();
           
          // p.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
           JOptionPane.showMessageDialog(null, "success tcnumber/password combination!","success",JOptionPane.INFORMATION_MESSAGE);
         
       }
       else JOptionPane.showMessageDialog(null, "Wrong tcnumber/password combination!");
      
       
    }//GEN-LAST:event_loginActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        Patient_Register register = new Patient_Register();
        register.setVisible(true);
        
        dispose();
        
         register.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_registerActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       
        Medical_Patient_Tracker GUI = new Medical_Patient_Tracker();
        GUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton login;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
