/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a.medical.patient.tracker;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Muzaffer
 */
public class StaffGUI extends javax.swing.JFrame {
    
    DBservice db = new DBservice();
    StaffRegister accountregister = new StaffRegister();
    
    /*
    Doctor doc;
    String StaffID;
    String Name;
    String Lastname;
    String password;
    
  //  boolean f = true;
    */

    /**
     * Creates new form StaffGUI
     */
    public StaffGUI() {
        initComponents();
        
        
        
         
    }
    
    
   
    /*
    public void doctor(){
        
        
        
       StaffID = jTextField1.getText();
       Name = jTextField2.getText();
       Lastname = jTextField3.getText();
       
       if(!StaffID.isEmpty()&& !Name.isEmpty()&& !Lastname.isEmpty()){
           
           doc = new Doctor(StaffID, Name, Lastname, null, null, null, password);
           
            JOptionPane.showMessageDialog(this, "Welcome back Doctor "+doc.Name,"Login",JOptionPane.INFORMATION_MESSAGE); 
           
            DoctorGUI doctorGuı = new DoctorGUI();
            doctorGuı.setVisible(true);
            
            dispose();
            
       }
      
        
        
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namefield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        Passwordtxtfield = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namefield.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(namefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 158, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 73, -1));
        jPanel1.add(Passwordtxtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 158, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "D626", "N642", "L57", "S52", "P40" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        
        StaffRegister register = new StaffRegister();
        register.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_RegisterActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
       
        
        String accounttype = jComboBox1.getSelectedItem().toString();
        String name = namefield.getText();
       
        String password = Passwordtxtfield.getText();
        
       if(db.checkStaffLogin(name,password)){
           
           String account = db.checkDoctorLogin(name, password);
           
           
           if(account.equals("D626")&&accounttype.equals("D626")){
               
               
               DoctorGUI docguı = new DoctorGUI(name,password);
                docguı.setVisible(true);
                Secretary_Medications GUI = new Secretary_Medications(name,password);
                
           JOptionPane.showMessageDialog(null, "Welcome Back DR "+name);
           dispose();
               
           }else 
           
            if(account.equals("N642")&&accounttype.equals("N642")){
               NurseGUI nurseguı = new NurseGUI(name,password);
                nurseguı.setVisible(true);
           JOptionPane.showMessageDialog(null, "Welcome Back Nurse  "+name);
           dispose();
               
           }else
                
                  if(account.equals("P40")&&accounttype.equals("P40")){
               PharmacistGUI GUI = new PharmacistGUI(name);
               GUI.setVisible(true);
               
           JOptionPane.showMessageDialog(null, "Welcome Back Pharmacist  "+name);
           dispose();
               
           }else
                
                 if(account.equals("L57")&&accounttype.equals("L57")){
                     LabTechnician GUI = new LabTechnician(name,password);
                     GUI.setVisible(true);
           JOptionPane.showMessageDialog(null, "Welcome Back LabTechnician  "+name);
           dispose();
               
           }else
                      
                      
           if(account.equals("S52")&&accounttype.equals("S52")){
               SecretaryGUI secretary = new SecretaryGUI();
                secretary.setVisible(true);
           JOptionPane.showMessageDialog(null, "Welcome Back Secretary  "+name);
           dispose();
               
           } else JOptionPane.showMessageDialog(null, "Ughh somethings Wrong...");
          
          
          // p.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
          
         
       }
       else JOptionPane.showMessageDialog(null, "Ughh somethings Wrong...");
    }//GEN-LAST:event_LoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login;
    private javax.swing.JPasswordField Passwordtxtfield;
    private javax.swing.JButton Register;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField namefield;
    // End of variables declaration//GEN-END:variables
}
